apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ default "default" .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.ssl }}
  rules:
    - host: {{ .Values.ingress.http }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 3005
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /capture
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 3005

